/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import java.util.Date;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alif
 */
public class ViewAppPayroll extends javax.swing.JFrame {

    private DefaultTableModel tableModel = new DefaultTableModel();
    private int no=1;
    private Double totalHarga = 0.0;
    
    /**
     * Creates new form ViewAppPayroll
     */
    public ViewAppPayroll() {
        initComponents();
        initUi();
    }
    
    private void initUi(){
        
//        DefaultComboBoxModel model = new DefaultComboBoxModel();
//        cbKomponenGaji.setModel(model);
//        model.addElement(new ModelGajiPegawai("Gaji Pokok"));
//        model.addElement(new ModelGajiPegawai("Tunjangan Transport"));
//        model.addElement(new ModelGajiPegawai("Tunjangan Anak"));
//        model.addElement(new ModelGajiPegawai("Tunjangan Kesehatan"));
//        model.addElement(new ModelGajiPegawai("Upah Lembur"));
//        model.addElement(new ModelGajiPegawai("Lain-lain"));
        
        tableModel.addColumn("No");
        tableModel.addColumn("Nama Komponen");
        tableModel.addColumn("Jumlah");
        tablePayroll.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDataKaryawan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        inputNIPKaryawan = new javax.swing.JTextField();
        inputNamaKaryawan = new javax.swing.JTextField();
        inputNoTelepon = new javax.swing.JTextField();
        inputTempatLahir = new javax.swing.JTextField();
        inputTanggalLahir = new com.toedter.calendar.JDateChooser();
        inputAlamat = new java.awt.TextArea();
        labelHeader = new java.awt.Label();
        panelDataKomponenGaji = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbKomponenGaji = new javax.swing.JComboBox<>();
        inputJumlahKomponenGaji = new javax.swing.JTextField();
        btnMasukan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePayroll = new javax.swing.JTable();
        btnSimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(815, 720));
        setPreferredSize(new java.awt.Dimension(815, 720));
        setSize(new java.awt.Dimension(815, 720));

        panelDataKaryawan.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Karyawan"));

        jLabel1.setText("NIP Karyawan");

        jLabel2.setText("Nama Karyawan");

        jLabel3.setText("Nomor Telepon");

        jLabel4.setText(" Tempat Lahir");

        jLabel5.setText("Tanggal Lahir");

        jLabel6.setText("Alamat");

        inputNIPKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNIPKaryawanActionPerformed(evt);
            }
        });

        inputNamaKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNamaKaryawanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDataKaryawanLayout = new javax.swing.GroupLayout(panelDataKaryawan);
        panelDataKaryawan.setLayout(panelDataKaryawanLayout);
        panelDataKaryawanLayout.setHorizontalGroup(
            panelDataKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataKaryawanLayout.createSequentialGroup()
                .addGroup(panelDataKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelDataKaryawanLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inputTanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDataKaryawanLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(panelDataKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDataKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputNamaKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputNIPKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputNoTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addGroup(panelDataKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDataKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(3, 3, 3)
                        .addGroup(panelDataKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDataKaryawanLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(inputTempatLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(inputAlamat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        panelDataKaryawanLayout.setVerticalGroup(
            panelDataKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataKaryawanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDataKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(inputNIPKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputTempatLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDataKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDataKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel5)
                        .addComponent(inputNamaKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(inputTanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDataKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputAlamat, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                    .addGroup(panelDataKaryawanLayout.createSequentialGroup()
                        .addGroup(panelDataKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelDataKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(inputNoTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        labelHeader.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelHeader.setText("Sistem Penggajian Karyawan");

        panelDataKomponenGaji.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Komponen Gaji"));

        jLabel7.setText("Pilih Komponen Gaji");

        jLabel8.setText("Masukan Jumlah");

        cbKomponenGaji.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbKomponenGaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihKomponenGaji(evt);
            }
        });

        javax.swing.GroupLayout panelDataKomponenGajiLayout = new javax.swing.GroupLayout(panelDataKomponenGaji);
        panelDataKomponenGaji.setLayout(panelDataKomponenGajiLayout);
        panelDataKomponenGajiLayout.setHorizontalGroup(
            panelDataKomponenGajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataKomponenGajiLayout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addGroup(panelDataKomponenGajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelDataKomponenGajiLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(inputJumlahKomponenGaji, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDataKomponenGajiLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(cbKomponenGaji, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDataKomponenGajiLayout.setVerticalGroup(
            panelDataKomponenGajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataKomponenGajiLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelDataKomponenGajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbKomponenGaji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDataKomponenGajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputJumlahKomponenGaji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        btnMasukan.setText("Masukan");
        btnMasukan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masukanKomponenGaji(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusKomponenGaji(evt);
            }
        });

        tablePayroll.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablePayroll);

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanData(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(panelDataKaryawan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelDataKomponenGaji, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnMasukan, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(labelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(285, 285, 285))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(labelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDataKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDataKomponenGaji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMasukan)
                    .addComponent(btnHapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSimpan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputNIPKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNIPKaryawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNIPKaryawanActionPerformed

    private void inputNamaKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNamaKaryawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNamaKaryawanActionPerformed

    private void pilihKomponenGaji(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihKomponenGaji
        // TODO add your handling code here:
        JComboBox cb = (JComboBox) evt.getSource();
        ModelGajiPegawai komponenGaji = (ModelGajiPegawai) cb.getSelectedItem();
    }//GEN-LAST:event_pilihKomponenGaji

    private void masukanKomponenGaji(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masukanKomponenGaji
        // TODO add your handling code here:
        Vector row = new Vector();
        ModelGajiPegawai komponenGaji = (ModelGajiPegawai) cbKomponenGaji.getSelectedItem();
        row.add(no++);
        row.add(komponenGaji.GetKomponenGajiPegawai());
        row.add(inputJumlahKomponenGaji.getText());
        Double komponen = Double.parseDouble(inputJumlahKomponenGaji.getText());
        this.totalHarga = this.totalHarga+komponen;
        tableModel.addRow(row);
        inputJumlahKomponenGaji.setText("0");
        cbKomponenGaji.setSelectedIndex(0);
    }//GEN-LAST:event_masukanKomponenGaji

    private void hapusKomponenGaji(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusKomponenGaji
        // TODO add your handling code here:
        int row = tablePayroll.getSelectedRow();
        Double totalHargaLama = (Double) tablePayroll.getValueAt(row, 2);
        this.totalHarga = this.totalHarga-totalHargaLama;
        tableModel.removeRow(tablePayroll.getSelectedRow());
        for(int i = 0; i < tableModel.getRowCount(); i++){
            tableModel.setValueAt(i+1,1,0);
            no = tableModel.getRowCount()+1;
        }
    }//GEN-LAST:event_hapusKomponenGaji

    private void simpanData(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanData
        // TODO add your handling code here:
    }//GEN-LAST:event_simpanData

    //------------Gagal pake cara MVC
    public void initBtnSimpan(java.awt.event.ActionListener Listener){
        btnSimpan.addActionListener(Listener);
    }
    
    public String getData(){
        // TODO add your handling code here:
        String nipKaryawan = inputNIPKaryawan.getText();
        String namaKaryawan = inputNamaKaryawan.getText();
        String noTelepon = inputNoTelepon.getText();
        Date tanggalLahir = inputTanggalLahir.getDate();
        String tempatLahir = inputTempatLahir.getText();
        String alamat = inputAlamat.getText();
        
        String message = "NIP Karyawan : " + nipKaryawan + "\nNama Karyawan : " + namaKaryawan + "\n No. Telepon : " + noTelepon + "\nTempat, Tanggal Lahir : " + tempatLahir+", "+ tanggalLahir+"\nAlamat : "+ alamat+"\nDetail Pendapatan : \n";
        
        for (int i =0;i<tableModel.getRowCount();i++){
            for(int j = 0;j<=2;j++){
                if(j==0){
                    message += (tableModel.getValueAt(i,j)+". ");
                }else if(j==1){
                    message += (tableModel.getValueAt(i,j)+" : ");
                }else{
                    message += (tableModel.getValueAt(i,j)+"\n");
                }
            }
        }
        message +="Total Pendapatan : "+this.totalHarga;
        return message;
    }
    //-----------Gagal pake cara MVC
    
    public void initComboBox(List<ModelGajiPegawai> komponenGaji){
        DefaultComboBoxModel model = new DefaultComboBoxModel(); // Init combo box
        cbKomponenGaji.setModel(model);
        for(ModelGajiPegawai komponen : komponenGaji){
            model.addElement(komponen);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAppPayroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAppPayroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAppPayroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAppPayroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAppPayroll().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnMasukan;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbKomponenGaji;
    private java.awt.TextArea inputAlamat;
    private javax.swing.JTextField inputJumlahKomponenGaji;
    private javax.swing.JTextField inputNIPKaryawan;
    private javax.swing.JTextField inputNamaKaryawan;
    private javax.swing.JTextField inputNoTelepon;
    private com.toedter.calendar.JDateChooser inputTanggalLahir;
    private javax.swing.JTextField inputTempatLahir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label labelHeader;
    private javax.swing.JPanel panelDataKaryawan;
    private javax.swing.JPanel panelDataKomponenGaji;
    private javax.swing.JTable tablePayroll;
    // End of variables declaration//GEN-END:variables
}
